import * as nodemailer from 'nodemailer'
import {EmailEntry} from "~/types/email";

const hostUrl = useRuntimeConfig().mailSecrets.HOST_URL

const footer = `
<br><br>
<br><br>
This email was automatically generated by Pulse, offered by the PSI chair.
<br><br>
Otto-Friedrich-Universität Bamberg
<br>An der Weberei 5 96047 Bamberg Germany
<br><a href=${hostUrl}/privacy-policy>Privacy Policy</a>`

const unsubscribeSpacing = `&nbsp;&middot;&nbsp;`

export const sendSignupLink = async (email: string, token: string, name: string) => {
    const url = `${hostUrl}/api/email-verification/${token}`;
    let body = `Hi ${name},<br><br>Thanks for signing up to Pulse! Please click the link below to verify your signup and complete it.<br><br><a href="${url}">Verify your signup</a>`
    body = body.concat(footer)

    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "Signup"
        },
        body: body
    }

    await sendEmail(mailOptions)
};

export const sendLoginLink = async (email: string, token: string, name: string) => {
    const url = `${hostUrl}/api/email-verification/${token}`;
    let body = `Hi ${name},<br><br>Please click the link below to log in to Pulse.<br><br><a href="${url}">Login</a>`
    body = body.concat(footer)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "Login"
        },
        body: body
    }

    await sendEmail(mailOptions)
};

export const sendPauseEmail = async (email: string, name: string, unsubscribeToken: string) => {
    let body = `Hi ${name},<br><br>We miss you! As you are ignoring us, we decided to stop sending you emails. Answer some questions to start receiving emails again.`
    body = body.concat(`<br><br><a href="${hostUrl}/">Answer some questions now</a>`)
    body = body.concat(footer)
    body = body.concat(unsubscribeSpacing + `<a href="${hostUrl}/unsubscribe/emails/${unsubscribeToken}">Stop receiving emails</a>`)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "We miss you!"
        },
        body: body
    }

    await sendEmail(mailOptions)
}

export const sendUnpauseEmail = async (email: string, name: string, unsubscribeToken: string) => {
    let body = `Hi ${name},<br><br> Welcome back! You are now receiving emails again. Don't let us down again and respond to the emails we are sending you!`
    body = body.concat(footer)
    body = body.concat(unsubscribeSpacing + `<a href="${hostUrl}/unsubscribe/emails/${unsubscribeToken}">Stop receiving emails</a>`)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "Welcome back!"
        },
        body: body
    }

    await sendEmail(mailOptions)
}

export const sendAnotherChance = async (email: string, name: string, unsubscribeToken: string) => {
    let body = `Hi ${name},<br><br> We are giving you another chance. You are now receiving emails again. Don't let us down again by responding the emails we are sending you!`

    body = body.concat(`<br><br><a href="${hostUrl}/">Start learning again</a>`)
    body = body.concat(footer)
    body = body.concat(unsubscribeSpacing + `<a href="${hostUrl}/unsubscribe/emails/${unsubscribeToken}">Stop receiving emails</a>`)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "We're giving you another chance!"
        },
        body: body
    }

    await sendEmail(mailOptions)
}

const generateQuestionsBody = (data: EmailEntry): string => {
    let body = ""

    for (const question of data.questions) {
        body = body.concat(`<br><br>`)
        if (question.group === "no-group") {
            body = body.concat(`<span>${question.page}</span>`)
        } else {
            body = body.concat(`<span>${question.page} – ${question.group}</span>`)
        }
        body = body.concat(`<br>`)
        body = body.concat(`<span><b>${question.text}</b></span>`)
        body = body.concat(`<br><a href="${hostUrl}/answer/question/${question.id}?token=${question.token}">Answer this</a>`)
    }

    return body
}

export const sendReminderEmail = async (email: string, data: EmailEntry, unsubscribeToken: string, name: string) => {
    let body = `Hi ${name},<br><br>There are open questions waiting for you! Answer all questions as soon as possible to keep them active.`
    // answer all questions
    body = body.concat(`<br><br><a href="${hostUrl}/answer/reminder/${data.token}">Answer all questions</a>`)
    body = body.concat(generateQuestionsBody(data))
    body = body.concat(footer)
    body = body.concat(unsubscribeSpacing + `<a href="${hostUrl}/unsubscribe/emails/${unsubscribeToken}">Stop receiving emails</a>`)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "There are questions waiting for you!"
        },
        body: body
    }

    await sendEmail(mailOptions)
}

export const sendWeeklyEmail = async (email: string, name: string, weeklyToken: string, unsubscribeToken: string) => {
    const url = `${hostUrl}/answer/weekly/${weeklyToken}`;
    let body = `Hi ${name},<br><br>Your weekly questions are here! Answer all questions within 7 days to hold your streak. <br><br><a href="${url}">Answer your weekly questions</a>`
    body = body.concat(footer)
    body = body.concat(unsubscribeSpacing + `<a href="${hostUrl}/unsubscribe/weekly-emails/${unsubscribeToken}">Stop receiving weekly emails</a>`)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "Your weekly questions are here!"
        },
        body: body
    }

    await sendEmail(mailOptions)
}

export const sendStreakLostEmail = async (email: string, name: string, unsubscribeToken: string) => {
    let body = `Hi ${name},<br><br>You lost your weekly streak. Answer your questions within 7 days to hold your streak.`
    body = body.concat(footer)
    body = body.concat(unsubscribeSpacing + `<a href="${hostUrl}/unsubscribe/weekly-emails/${unsubscribeToken}">Stop receiving weekly emails</a>`)
    const mailOptions: IEmailData = {
        head: {
            to: email,
            subject: "You lost your weekly streak!"
        },
        body: body
    }

    await sendEmail(mailOptions)
}

interface IEmailData {
    head: { to: string, subject: string },
    body: any
}

export const sendEmail = async (data: IEmailData) => {
    const transporter = nodemailer.createTransport({
        host: useRuntimeConfig().mailSecrets.EMAIL_HOST,
        port: 587,
        secure: false,
        requireTLS: true,
        auth: {
            user: useRuntimeConfig().mailSecrets.EMAIL_USER,
            pass: useRuntimeConfig().mailSecrets.EMAIL_PASS
        },
    })

    const mailOptions = {
        from: 'Pulse <pulse.psi@uni-bamberg.de>',
        to: data.head.to,
        subject: data.head.subject,
        html: "<p>" + data.body + "</p>"
    }
    await transporter.sendMail(mailOptions)
    transporter.verify(function (error, success) {
        if (error) {
            console.log(error);
        } else if (success) {
            console.log("Server is ready to take our messages");
        } else {
            console.log("Server is not ready to take our messages");
        }
    });
}
